version: '3.1'
services:
  mysql:
    image: mysql:5.7
    ports:
    - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sugar
      MYSQL_USER: sugar
      MYSQL_PASSWORD: sugar
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root

  mongo-express:
    image: mongo-express
    restart: always
    ports:
    - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
  phpmyadmin:
    # restart: always
    image: phpmyadmin/phpmyadmin
    ports:
    - '8888:80'
    - '9999:9000'
    environment:
      MYSQL_USERNAME: sugar
      MYSQL_PASSWORD: sugar
      MYSQL_ROOT_PASSWORD: root
      PMA_HOST: mysql
    depends_on:
    - mysql
  web:
    image: thecodingmachine/php:7.1-v1-apache-node8
    hostname: 'sugarcrm'
    environment:
      PHP_INI_ERROR_REPORTING: E_ERROR
      MYSQL_NAME: 'mysql'
      MYSQL_PORT: 'tcp://mysql:3306'
      APACHE_EXTENSION_REWRITE: 1
      APACHE_EXTENSION_HEADERS: 1
      APACHE_EXTENSION_EXPIRES: 1
      APACHE_LOG_DIR: '/var/log/apache2'
      #      PHP_EXTENSION_XDEBUG: 1
      PHP_EXTENSIONS: bcmath blackfire calendar dba exif gd gettext gmp imap intl ldap mcrypt memcached mongodb sockets sysvmsg sysvsem sysvshm pcntl tidy xdebug xmlrpc xsl
      PHP_INI_XDEBUG__REMOTE_AUTOSTART: 1
      #serverName=SomeName, where SomeName is the name of the server configured in Settings / Preferences | Languages & Frameworks | PHP | Servers
      PHP_IDE_CONFIG: "serverName=Docker"
    depends_on:
    - mysql
    - mongo
    ports:
    - 8080:80
    volumes:
    - .:/var/www/html:rw